### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1243]
A house-keeping improvement.
Check why the warning is raised here : https://github.com/pytorch/ignite/actions/runs/214923621
and fix if necessary.

For Hacktoberfest contributors, feel free to ask questions for details if any and say that you would like to tackle the issue.
Please, take a look at [CONTRIBUTING guide](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md).

**Comment by rexdivakar** [comment]
I would love to work on this pls assign it on my name @vfdev-5

**Comment by sdesrozis** [comment]
@rexdivakar Thank you for your help !!

**Comment by rexdivakar** [comment]
Due to the flexible nature of the required inputs depending on the route, not all of the possible paramters can be listed in code-style.yml, so you will see this warning under normal usage of the action. As long as you see a 200 response code at the bottom of the output, everything should have worked properly and you can ignore the warnings. The response code will appear at the bottom of the output from the action and looks like:

< 200 451ms

**Comment by vfdev-5** [comment]
OK, let's then just update `stefanzweifel/git-auto-commit-action` to the latest version 4.
```
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "autopep8 fix"
```
