### ISSUE TITLE
0.2.1 to 0.4.1 OutputHandler upgrade question

### ISSUE THREAD

**Issue by g-karthik** [pytorch/ignite#1281]
## ❓ Questions/Help/Support

I'm upgrading the version of ignite in my codebase from 0.2.1 to 0.4.1.

I see that `OutputHandler` no longer accepts `another_engine` as an argument and pull request https://github.com/pytorch/ignite/pull/531/ suggests using `global_step_transform` in place of this.

My previous piece of code (ignite 0.2.1) was like this:
`        tb_logger.attach(validator, log_handler=OutputHandler(tag="valid", metric_names=list(valid_metrics.keys()), another_engine=trainer), event_name=Events.EPOCH_COMPLETED)
`

If I want to retain the same behavior as the above line of code while upgrading to version 0.4.1, it looks like I need to replace `another_engine=trainer` with `global_step_transform=lambda x: trainer.state.iteration`. Is that an accurate understanding? It seems from the above pull request that I should do so, but then again, that pull request itself was for 0.2.1 where you began the deprecation of `another_engine` with a warning, so maybe there's some more context I need to better understand this.

@vfdev-5

**Comment by g-karthik** [comment]
I think I figured this out, I need to use the `global_step_from_engine()` method from `ignite.handlers`. Closing for now, but @vfdev-5 it would be great if you also confirmed my understanding!

**Comment by vfdev-5** [comment]
@g-karthik yes, I think your understanding is correct. For the context, we removed `another_engine` since 0.4.0 and suggest to use `global_step_transform` instead due to limitations of  `another_engine`, namely #519 .

When using `global_step_transform`, we can either set it up with `global_step_from_engine` as it is done here:
https://github.com/pytorch/ignite/blob/002b595daa8a8345286c5e096c33e278948686a7/examples/contrib/mnist/mnist_with_tensorboard_logger.py#L119-L125

 or provide a lambda like here:
https://github.com/pytorch/ignite/blob/002b595daa8a8345286c5e096c33e278948686a7/examples/contrib/mnist/mnist_with_wandb_logger.py#L113-L119
