### ISSUE TITLE
Improve typing in engine

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1513]
## 🚀 Feature

The following code may be fail if `max_epochs is None`:

https://github.com/pytorch/ignite/blob/a756f9ca956ee0ee72bb61401a87a6eaf249dbba/ignite/engine/engine.py#L839-L842

https://github.com/pytorch/ignite/blob/a756f9ca956ee0ee72bb61401a87a6eaf249dbba/ignite/engine/engine.py#L562-L566

Maybe, we have to add additional check of `max_epochs is not None` and remove `# type: ignore[operator]`.

@gruebel what do you think ?

**Comment by gruebel** [comment]
I took a very long view on the code and I think it is a really good idea to check for `max_epochs is not None`, because right now, there can be edge cases like `max_epochs is None` and `epoch_length is not None` this will result in a Runtime Error in the `_is_done` method.
https://github.com/pytorch/ignite/blob/3affd95f9480b4f6a9070d800d8505bc3e80e0dc/ignite/engine/engine.py#L560-L567

and as long as the `_is_done` check doesn't raise an error here `max_epochs` will also be not `None`
https://github.com/pytorch/ignite/blob/a756f9ca956ee0ee72bb61401a87a6eaf249dbba/ignite/engine/engine.py#L835-L843

**Comment by vfdev-5** [comment]
@gruebel thanks for the feedback. Can I assign this issue to you ?

**Comment by gruebel** [comment]
Sure 😄  will make a PR ready today or latest tomorrow.
