### ISSUE TITLE
Update cifar10 example, validation with amp

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1666]
Currently, we provide AMP option for the training, but model's evaluation still run on plain f32. Recently, we merged [transformers example](https://github.com/pytorch/ignite/tree/master/examples/contrib/transformers) where evaluation takes amp into account : https://github.com/pytorch/ignite/blob/master/examples/contrib/transformers/main.py#L367

The idea is to make cifar10 example compatible as transformers example:

Replace 
https://github.com/pytorch/ignite/blob/7753eabc5af8bed2cca4713805613adfbc460a8e/examples/contrib/cifar10/main.py#L86-L87

by 
https://github.com/pytorch/ignite/blob/7753eabc5af8bed2cca4713805613adfbc460a8e/examples/contrib/transformers/main.py#L88-L89

and create similar `create_evaluator` helper method.

**Comment by Moh-Yakoub** [comment]
I'd like to pick this one up, I have a question though.

Is the idea to update that method invocation https://github.com/pytorch/ignite/blob/master/examples/contrib/cifar10/main.py#L86 to pass AMP into evaluation as well? 

Since the evaluator https://github.com/pytorch/ignite/blob/master/ignite/engine/__init__.py#L370 doesn't have the param we have the option with either 
1. Add an optional param for the method.
2. Just create a custom evaluator method for the sake of the example.

I am leaning towards 1 as it offers more generalized solution, any preference on that?

**Comment by vfdev-5** [comment]
I updated the description to make it more explicit.
I'd say, let's do 2nd option for this issue. But I agree in a long term we can replace that with another solution that could join recently merged PR for AMP: https://github.com/pytorch/ignite/pull/1589 (cc @ydcjeff)
