### ISSUE TITLE
Fix flaky test with time profiler

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#1824]
From time to time, tests related to time profiler are failing like there:
```
FAILED tests/ignite/contrib/handlers/test_time_profilers.py::test_pos_event_filter_threshold_handlers_profiler
= 1 failed, 702 passed, 29 skipped, 314 deselected, 134 warnings in 235.26s (0:03:55) =
```
https://github.com/pytorch/ignite/pull/1821/checks?check_run_id=2141981144

The idea is to inspect and analyse the failure case and propose a fix.

**Comment by rushabh-v** [comment]
Hi @vfdev-5, I tried investigating the cause, and here is what I found.

The error message says that the result contains `not triggered` but it should contain a number. Now the string `not triggered` is returned because of the line: https://github.com/pytorch/ignite/blob/17435926c54234b9aa90c6487d183795a030def6/ignite/contrib/handlers/time_profilers.py#L614

The data is an element of self.event_handlers_times, And from the following lines, it looks like it would be empty when `t < self.EVENT_FILTER_THESHOLD_TIME` (`t = Timer.value()` and `self.EVENT_FILTER_THESHOLD_TIME = 0.0001`):
https://github.com/pytorch/ignite/blob/17435926c54234b9aa90c6487d183795a030def6/ignite/contrib/handlers/time_profilers.py#L512-L513

There is no issue if I am not misunderstanding it. A simple update in the tests would work in that case.

I can send a PR if you agree. Thanks.

**Comment by vfdev-5** [comment]
@rushabh-v thanks for investigating this issue ! Yes, I agree, it should be about test fix. 

> I can send a PR if you agree. 
What would be the fix according to your analysis ? Yes, you can send a draft PR and we'll iterate over.

**Comment by rushabh-v** [comment]
Hi @vfdev-5, I think if the result is an instance of `str`, we can assert whether it is equal to "not triggered" else we can assert the current expression.

>you can send a draft PR and we'll iterate over.

Sure.

**Comment by vfdev-5** [comment]
Let's close this issue as CI platform related.
