### ISSUE TITLE
Need help about https://github.com/pytorch/ignite/blob/master/examples/notebooks/EfficientNet_Cifar100_finetuning.ipynb

### ISSUE THREAD

**Issue by ReloJeffrey** [pytorch/ignite#2112]
## Help

I want to reproduce the result of efficientnet on cifar100. But I even cannot install nvidia/apex pacakge in EfficientNet_Cifar100_finetuning.ipynb. Can you give some suggestions or another more friendly implement. Thanks.

**Comment by vfdev-5** [comment]
Hi @ReloJeffrey , if you can use docker container, we have a number of pre-built images like:

- [pytorchignite/apex:latest](https://hub.docker.com/r/pytorchignite/apex)
- [pytorchignite/apex-vision:latest](https://hub.docker.com/r/pytorchignite/apex-vision)

with nvidia/apex installed.

See details here: https://github.com/pytorch/ignite#using-pre-built-images

Otherwise, you can install nvidia/apex as here:

https://github.com/pytorch/ignite/blob/de4cff3f28edcbbb1ed82d199845b8b32088b7d3/docker/main/Dockerfile.apex#L16-L22

**Comment by sdesrozis** [comment]
Hello @ReloJeffrey 

The issue you faced is related to the mismatch of the CUDA versions of the preinstalled PyTorch binaries and the compilation tools found to build apex.

I solved this by matching the version of CUDA used and the PyTorch version
```
%env CUDA_HOME=/usr/local/cuda-10.1
```
and
```
!pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
```

Sorry for this, it is not easy to track such an issue. 

HTH

**Comment by vfdev-5** [comment]
Let's close this issue as answered. Feel free to reopen if needed
