### ISSUE TITLE
Improve typing hints for Engine and helper methods

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2356]
## 🚀 Feature

1) Let's improve typing hints for process_function arg:
- https://github.com/pytorch/ignite/blob/8a1de70e2152936ffcb051f3bd618138130626ec/ignite/engine/engine.py#L122
We have to provide the signature: [Engine, Any] -> Any in mypy recognizable way

Also here: https://github.com/pytorch/ignite/blob/8a1de70e2152936ffcb051f3bd618138130626ec/ignite/engine/deterministic.py#L179

2) Let's improve typing hints for `prepare_batch` and `output_transform` for `create_supervised_trainer` and `create_supervised_evaluator`.

https://github.com/pytorch/ignite/blob/8a1de70e2152936ffcb051f3bd618138130626ec/ignite/engine/__init__.py#L52-L53

3) Provide example of usage of `prepare_batch` and `output_transform` in the docstring: https://pytorch.org/ignite/generated/ignite.engine.create_supervised_trainer.html

cc @Priyansi

**Comment by louis-she** [comment]
Many of the callbacks like `prepare_batch` are called with keyword arguments in many places in the source code. But `typing.Callable` can only annotated positional arguments, not keyword arguments or more complicated cases.

So if we change the annotation of the callbacks by `typing.Callable`.  `mypy` will complaint about it where there is a invokation with keyword arguments.

`typing.Protocol` is more suitable to annotated callbacks but it's available since Python 3.8, so for the moment we should skip this.

![](https://cdn.discordapp.com/attachments/844863443893878824/921370957401186344/unknown.png)

![](https://cdn.discordapp.com/attachments/844863443893878824/921370842267533353/unknown.png)

**Comment by vfdev-5** [comment]
@louis-she would you like to fix points 1 and 3 ?

**Comment by louis-she** [comment]
> @louis-she would you like to fix points 1 and 3 ?

Of course, i will work on it.

**Comment by louis-she** [comment]
https://github.com/pytorch/ignite/pull/2382
