### ISSUE TITLE
[BUG] missing key "percentage" with progressbar handler

### ISSUE THREAD

**Issue by jiangxiluning** [pytorch/ignite#526]
when iteration compeled, tqdm claimed the "percentage" keyerror.

ignite == 0.2.0
tqdm == 4.32.1

**Comment by kilsenp** [comment]
I have the same problem, did you find a solution?

**Comment by vfdev-5** [comment]
@kilsenp please provide the code with the problem. Otherwise try to install ignite from master:
```bash
pip install --upgrade git+https://github.com/pytorch/ignite
```

**Comment by kilsenp** [comment]
I found the issue, it happens when the dataloader takes more iterations than originally specified. 

If there are more iterations, no total will be set
https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L322

so that this branch is executed and no percentage is calculated:
https://github.com/tqdm/tqdm/blob/master/tqdm/_tqdm.py#L452
The bar format however still always requires percentage in the format_dict.

This means to solve it, one has to make sure that the dataloader length stays constant.

Not sure if it makes sense to check for this somehow.

**Comment by vfdev-5** [comment]
@kilsenp thanks for the details! Yes, I think this is out of scope of ignite. I labelled this issue as question so that it'll help other users.

**Comment by jiangxiluning** [comment]
@kilsenp try with lower version of tqdm

**Comment by EliasVansteenkiste** [comment]
Same issue with:
```
$ pip3 freeze | grep ignite
pytorch-ignite==0.3.0
$ pip3 freeze | grep tqdm
tqdm==4.35.0
```

Stack trace:
```
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 392, in _run_once_on_dataset
    self._fire_event(Events.ITERATION_COMPLETED)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 345, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ignite/contrib/handlers/tqdm_logger.py", line 245, in __call__
    logger.pbar.update()
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 1164, in update
    self.display()
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 1376, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 1022, in __repr__
    return self.format_meter(**self.format_dict)
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 482, in format_meter
    return bar_format.format(bar='?', **format_dict)
KeyError: 'percentage'
```
For us it happened randomly, sometimes after 16 hours of training.

**Comment by EliasVansteenkiste** [comment]
> @kilsenp try with lower version of tqdm

Which lower version did you use?
