### ISSUE TITLE
Possible to use ignite for training but not eval?

### ISSUE THREAD

**Issue by sshleifer** [pytorch/ignite#577]
I am using ignite for my training engine, and just want to run a custom evaluation function on some data that ignite shouldn't care about once after every epoch. 
something like

trainer.

`trainer.add_event_handler(Events.EPOCH_COMPLETED, run_eval)`
where run_eval has no arguments.

1) What is the correct way to do this?
2) Additionally, is it possible to have training run on multiple GPUs but my run_eval function only run on one GPU?

This only runs once, for some reason, even if I wrap `run_eval` in a lambda.
do I need to fire some events to get it to run again/something more complicated?

I have read the concepts but my metrics can't easily be accumulated.
Thanks!

**Comment by vfdev-5** [comment]
@sshleifer if you could give more details on what you would like to do in `custom evaluation function` and whole the training pipeline. If this `run_eval` is standalone and does not need to iterate over batches etc. So, yes, call it as I suggested
```python
trainer = ...
trainer.add_event_handler(Events.EPOCH_COMPLETED, lambda engine: run_eval())
```

> Additionally, is it possible to have training run on multiple GPUs but my run_eval function only run on one GPU?

In this case your model should not be DDP, right ?
if it is the case, you can just specify it with `dist.get_rank() == 0` and tell other GPUs to wait ?
```python
@trainer.on(Events.EPOCH_COMPLETED)
def run_eval_wrapper(engine):
    if dist.get_rank() == 0:
        run_eval()
    else:
        # tell other gpus to wait
```

> I have read the concepts but my metrics can't easily be accumulated.

Could you please provide more details on that. Maybe we could improve our metrics module and provide more helpers. 
Otherwise, one can store whole predictions and targets with `EpochMetric` and then use functions as `sklearn.metrics.roc_auc_score` to compute metrics.


Tell me if you need more support.

**Comment by sshleifer** [comment]
This `dist.get_rank()` construction is exactly what I needed. Thank you!
