### ISSUE TITLE
Handler Events as flags

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#710]
Idea is to provide the following flexibility:
```python

@trainer.on(Events.ITERATION_STARTED(once=1) | Events.ITERATION_STARTED(every=10) | Events.COMPLETED)
def execute_some_handler(_):
    pass
```
such that `execute_some_handler` is triggered at the first iteration and at 10th, 20th, ...etc and in the end of the training.

**Comment by justusschock** [comment]
what we could most likely implement way easier is to provide something like 
```python
@trainer.on(Events.ITERATION_STARTED(once=1), Events.ITERATION_STARTED(every=10) , Events.COMPLETED)
def execute_some_handler(_):
    pass
```
where each argument given there is concatenated with `|`

**Comment by vfdev-5** [comment]
@justusschock here is a subtle detail is that the signature of 
```
@trainer.on(<Event>, *args, **kwargs)
```
so, `Events.ITERATION_STARTED(once=1), Events.ITERATION_STARTED(every=10) , Events.COMPLETED` means `<Event>=Events.ITERATION_STARTED(once=1)` and others are `*args`...

**Comment by justusschock** [comment]
Exactly, that's why we would just have to introduce additional checks there, which will wrap them to a function, but this is way easier to implement than having them connected by the user as a boolean via `|`. Because currently I see no way to implement flagging behaviour without having to previously evaluate them for each possible event value.

If you're okay on separating them with ',' instead of '|', I will start implementing this.
