### ISSUE TITLE
Engine state object

### ISSUE THREAD

**Issue by jasonkriss** [pytorch/ignite#80]
We touched on this in #37 and #52 but I wanted to make a dedicated issue to discuss it.

## Motivation
- avoid the proliferation of `current_*` attributes on `Engine`s
- allow for handlers to pass state between each other

## Proposal
- similar to torchnet approach
- we create a new `state` object at the start of `Engine#run` and it is updated throughout the run
- `Trainer` state can have the following to start: dataloader, history, iteration, epoch, max_epochs
- `Evaluator` state can have the following to start: dataloader, history, iteration
- final state is returned by `Engine.run`

## Open questions
- do we still need to pass engine to event handlers or can we just pass state?
- should state just be a dict or an actual object? (@elanmart I think you had some thoughts on this)

What do you all think?

**Comment by alykhantejani** [comment]
1) I think if we are moving all `current_*` fields to the `state` object then we should instead pass this to the handlers instead of the engine. This should be a backwards compatible change as `trainer.current_iteration` will be the same as `state.current_iteration` (except for the incorrect naming)

2) I think we should keep it as an actual object, that way we can define functions like `clear()` for convenience. Also if it's a dict we can't do things like `state.current_iteration` but instead must do `state['current_iteration']` which IMO is uglier

**Comment by elanmart** [comment]
I agree that object will be a better solution, as the dot-notation is nicer, and my editor will be able to give me some auto-completion. 

I also agree that it should be passed to handlers. Not sure if `state` needs dataloader though (but its a minor detail).

**Comment by jasonkriss** [comment]
@elanmart when i was using torchnet, i found it nice to have the dataloader on the state as i could then wrap it in tqdm in an event handler on each epoch. Like you said though, pretty minor.

I think I'm with you guys on using an object. @alykhantejani what would `clear()` do exactly? Are we okay with users being able to add arbitrary data to the state object in event handlers?

**Comment by alykhantejani** [comment]
So, I think we have 3 things in play here:

`Engine`: - This should probably hold the reference to the dataloader 
`State`: - should hold current state of the engine i.e. `current_iteration` etc. And also and user-defined state. 
`History`: - Holds the historical results returned from the update function in the engine. 

If we store a reference to the state and the history in the engine itself, then the current handler API doesn't have to change i.e. users can access the state via `trainer.state` and history via `trainer.history` as well as the dataloader.

My idea of `clear()` would be an easy way for users to clear up any user-defined state that they were passing around between handlers (without them having to explicitly do `del state.my_list`). Not sure how this would be implemented, as we probably don't want it clearing `current_iteration` etc.

Does that make sense? Do you see any downsides of this separation except for user education (which I  think we need to do anyway - which reminds me we need to re-write a lot of the README after all of these changes)

**Comment by jasonkriss** [comment]
I'm thinking once we resolve this issue and #78, things are gonna stabilize a lot. I was waiting for that to happen but then was planning on bringing the README and all docstrings fully up to date.

I understand `clear()` now. Makes sense. I'd say let's maybe hold off on that for now though just so it doesn't block the initial implementation. It's a convenience that we can add on later.

I don't think we should worry too much about changing the API right now since we are in alpha. I'd rather get the API right. That said, once a couple of these more important issues are resolved, I think we should start thinking about putting out a formal release. I imagine a lot of users are holding off from using ignite until they see that stabilization.

My personal preference would be to have a single `state` object passed to handlers. Like you said, this represents the current state of the engine/run. For that reason, I think dataloader belongs on the `state` object. It gets passed into `run` and so is connected to that particular run of the trainer. `state` is ephemeral and only relevant for a single `run` so I don't think we should attach it to the trainer itself.

I have some thoughts on `history` but I'll address that in #78 since I think its a lil more relevant there.

**Comment by alykhantejani** [comment]
I agree about changing the API - it's fine now that we're in alpha, but I'd like to see it stabilize soon (after these PR's hopefully), and a version on conda/pypi would be good.

I see your point about the dataloader being part of the state, and don't have a problem with that.

However, I think the engine will need access to the state, to access and update things like `current_iteration` etc. which is why I feel it makes sense to be a member of the engine that is reset when `run()` is called. 

On the `History`,  we could probably merge this into `State` or make it a member of state as it also refers to the current run's state. If we do this, then state is the only thing we need to pass around to handlers as they shouldn't be meddling with other things on the Engine.

What do you think about that? 

So maybe it's best we try and get this merged first, then tackle #78, then update docs, examples etc.

**Comment by alykhantejani** [comment]
@jasonkriss is this something you'd want to work on? If so, do you mind starting a PR and we can iterate there? If you're busy that's cool - I can try and get one together Monday

**Comment by jasonkriss** [comment]
@alykhantejani This sounds great. Yep I can take this one. I like that plan of action! Let's do that. 

You are correct that the engine needs to access state, but I don't think that necessitates storing it as a member on `Engine`.  I like the [torchnet approach](https://github.com/pytorch/tnt/blob/master/torchnet/engine/engine.py#L9) of creating the the `state` object at the beginning of `Engine#run` and then passing it to the methods that need it (i.e `_run_once_on_dataset` and `_fire_event`). I like this approach for two reasons: it's more explicit and `state` is ephemeral. What do you think?

Once we agree on that part one way or the other, I'll open a PR to remove History and add all `state` functionality.

**Comment by alykhantejani** [comment]
@jasonkriss that approach sounds good to me :)
