### ISSUE TITLE
Why the engine doesn't release the train dataloder processes before validating ?

### ISSUE THREAD

**Issue by mikael10j** [pytorch/ignite#840]
Hi all,
Facing memory (RAM) issues when using num workers > 0 in dataloader, I have noticed that with ignite the processes of the train loader are not released before validation starts. This leads to doubling the number of processes used during validation. Here is a toy example:

```Python
class MyDataset(Dataset):
    
    def __init__(self, n):
        self.len = n
    
    def __len__(self):
        return self.len
    
    def __getitem__(self, idx):
        return np.random.rand(2*1855).astype(np.float32)

train_dataset = ConcatDataset([MyDataset(10000) for _ in range(60)])
train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True, num_workers=4, drop_last=True)
val_dataset = ConcatDataset([MyDataset(10000) for _ in range(10)])
val_loader = DataLoader(val_dataset, batch_size=256, shuffle=True, num_workers=4, drop_last=True)

device = torch.device('cuda')

model = torch.nn.Sequential(torch.nn.Linear(2*1855, 1), torch.nn.ReLU())
model.to(device)

optim = torch.optim.Adam(model.parameters())
    
def train_step(engine, batch):
    model.train()
    optim.zero_grad()
    image = batch.to(device)
    l = model(image).sum()
    l.backward()
    optim.step()

def val_step(engine, batch):
    model.eval()
    optim.zero_grad()
    image = batch.to(device)
    l = model(image).sum()

trainer = Engine(train_step)
validater = Engine(val_step)
    
@trainer.on(Events.EPOCH_COMPLETED)
def validate(engine):
    validater.run(val_loader)
    
trainer.run(train_loader, 3)
```
and the memory-profiler output:

![test_3_epoch_ignite](https://user-images.githubusercontent.com/10218967/76869481-b02f5180-6868-11ea-8466-1aab428e21de.png)

We clearly see an overlapping during the validating phase and the number of processes doubled (asked for 4 but got 8).

If I replace ignite by a classic training loop:

```Python
for epoch in range(3):
    for i, batch in enumerate(train_loader):
        train_step(batch)
    
    for i, batch in enumerate(val_loader):
        val_step(batch)
```
I get
![test_3_epoch_no_ignite](https://user-images.githubusercontent.com/10218967/76870197-afe38600-6869-11ea-904b-51c7a5b3ab6b.png)

Is it the expected behaviour ? Or am I doing something wrong ?

**Comment by vfdev-5** [comment]
@mikael10j thanks for the report. This is a good question and describes rather common situation : training + validation after an epoch. However, in general case, we can consider epoch length to be unrelated to the length of the dataloader.

Such behaviour may seem OK as there are two engines: trainer and validater and only trainer can be aware of the second engine. Internally, every engine keeps a ref to `iter(dataloader)` inside until the end of the run. That's why probably you see 8 children: 4 from train loader and 4 for validation loader. Can we free internal the ref to `iter(dataloader)` once iterator is done, then trigger all necessary events and reassign the ref to restarted iterator ? Probably, this is possilbe, however I feel that this is a particulat case: if you attach `validate` function for example on `Events.ITERATION_COMPLETED(every=1000)`, there still be 8 children. Similarly to the bare pytorch code:
```
iteration = 0
for epoch in range(3):
    for i, batch in enumerate(train_loader):
        train_step(batch)
        iteration += 1
        if iteration % 1000 == 0:
            for i, val_batch in enumerate(val_loader):
                 val_step(val_batch)
```


Memory issues, may be also addressed by explicitly cleaning up stored `batch` and `output` if are not used in the handlers :
```python
@trainer.on(Events.EPOCH_COMPLETED)
def clean(engine):
    engine.state.output = None
    engine.state.batch = None

@trainer.on(Events.EPOCH_COMPLETED)
def validate(engine):
    validater.run(val_loader)
```

PS: How do you produce these curves ?

**Comment by mikael10j** [comment]
@vfdev-5 thank you very much for the explanation and the tips. I've used memory-profiler: https://github.com/pythonprofilers/memory_profiler
