### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by karfly** [pytorch/ignite#95]
Tried to run scripts from /examples, but failed.
I got 2 errors:

1. `ImportError: No module named 'ignite.handlers.logging'`
2. `ImportError: cannot import name 'Evaluate'`

Tried to find source code for them and didn't manage to find anything. This functionality is just not implemented yet or I'm doing something wrong?

**Comment by jasonkriss** [comment]
@karfly Sorry about that! There has been some very recent breaking changes (for the better!). Things have settled dow now though so I am hoping to bring those examples and the docs up to date in the next few days.

**Comment by alykhantejani** [comment]
I'll also be trying to close out the issues related to API changes this weekend.

**Comment by amrsharaf** [comment]
When you change the API could you please release a separate version and leave the old API working?

**Comment by alykhantejani** [comment]
@amrsharaf sorry about the recent API changes, this is due to us still being in alpha. I hope now the API stays more stable and is hopefully better for the end user. We will be releasing a proper release soon (with wheels and conda packages etc) and after this any breaking changes will be properly semver'd so that you can use and depend on a specific version
